# Generated by Django 6.0.3 on 2026-03-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_eco_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eco',
            name='subtitulo',
        ),
        migrations.AlterField(
            model_name='eco',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eco',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eco',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eco',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
